---
version: "3.8"
services:

  python:
    build:
      context: .
    container_name: book_app
    stdin_open: true
    tty: true
    depends_on:
      - mysql_db
    environment:
      - MYSQL_HOST=mysql_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=bookstore_db
    networks:
      - myntw1

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bookstore_db
    restart: always
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
        - -uroot
        - -ppassword
      retries: 5
      timeout: 5s
      interval: 5s
      start_period: 30s
    networks:
      - myntw1
    volumes:
      - ./mydata:/var/lib/mysql
    
networks:
  myntw1:
