# docker compose up -d
# docker exec -it python_app bash

version: "3.8"

services:

        python:
                build:
                        context: .
                container_name: "python_app"
                restart: always
                stdin_open: true    # Equivalent to -i 
                tty: true           # Equivalent to -t 
               
